/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const LayoutSettings = IDL.Record({
  'watermarkText' : IDL.Text,
  'qrPayload' : IDL.Text,
  'headerColor' : IDL.Text,
  'watermarkOpacity' : IDL.Nat,
  'showQrCode' : IDL.Bool,
  'footerLayout' : IDL.Variant({
    'twoColumn' : IDL.Null,
    'centered' : IDL.Null,
  }),
  'showWatermark' : IDL.Bool,
  'signatureLayout' : IDL.Variant({
    'stacked' : IDL.Null,
    'sideBySide' : IDL.Null,
  }),
  'footerText' : IDL.Text,
});
export const GlobalMasterTemplate = IDL.Record({
  'signature' : IDL.Opt(ExternalBlob),
  'logo' : IDL.Opt(ExternalBlob),
  'layout' : LayoutSettings,
  'businessName' : IDL.Text,
  'businessAddress' : IDL.Text,
  'optionalCustomFieldValue' : IDL.Opt(IDL.Text),
  'stamp' : IDL.Opt(ExternalBlob),
  'optionalCustomFieldLabel' : IDL.Opt(IDL.Text),
  'adminId' : IDL.Text,
});
export const TemplateResult = IDL.Variant({
  'unexpectedError' : IDL.Text,
  'alreadyExists' : IDL.Null,
  'unauthorizedField' : IDL.Null,
  'notFound' : IDL.Null,
  'success' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LoanType = IDL.Variant({
  'home' : IDL.Null,
  'education' : IDL.Null,
  'personal' : IDL.Null,
  'business' : IDL.Null,
  'vehicle' : IDL.Null,
});
export const LoanProcessingData = IDL.Record({
  'id' : IDL.Text,
  'loanType' : LoanType,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
  'processingCharge' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const DocumentContent = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'adminId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomTemplate' : IDL.Func(
      [IDL.Text, GlobalMasterTemplate],
      [TemplateResult],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createLoanProcessingRecord' : IDL.Func([LoanProcessingData], [], []),
  'deleteLoanProcessingRecord' : IDL.Func([IDL.Text], [], []),
  'getAllDocumentContents' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'contents' : IDL.Vec(IDL.Text),
          'businessTemplates' : IDL.Opt(GlobalMasterTemplate),
        }),
      ],
      ['query'],
    ),
  'getAllLoanProcessingRecords' : IDL.Func(
      [],
      [IDL.Vec(LoanProcessingData)],
      ['query'],
    ),
  'getAllTemplates' : IDL.Func([], [IDL.Vec(GlobalMasterTemplate)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomTemplateById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(GlobalMasterTemplate)],
      ['query'],
    ),
  'getDocumentContent' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(DocumentContent)],
      ['query'],
    ),
  'getGlobalTemplate' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(GlobalMasterTemplate)],
      ['query'],
    ),
  'getLoanProcessingRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(LoanProcessingData)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCustomTemplate' : IDL.Func(
      [IDL.Text, GlobalMasterTemplate],
      [TemplateResult],
      [],
    ),
  'updateGlobalTemplate' : IDL.Func([IDL.Text, GlobalMasterTemplate], [], []),
  'updateLoanProcessingRecord' : IDL.Func(
      [IDL.Text, LoanProcessingData],
      [],
      [],
    ),
  'updateMultipleDocumentTypes' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, DocumentContent))],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const LayoutSettings = IDL.Record({
    'watermarkText' : IDL.Text,
    'qrPayload' : IDL.Text,
    'headerColor' : IDL.Text,
    'watermarkOpacity' : IDL.Nat,
    'showQrCode' : IDL.Bool,
    'footerLayout' : IDL.Variant({
      'twoColumn' : IDL.Null,
      'centered' : IDL.Null,
    }),
    'showWatermark' : IDL.Bool,
    'signatureLayout' : IDL.Variant({
      'stacked' : IDL.Null,
      'sideBySide' : IDL.Null,
    }),
    'footerText' : IDL.Text,
  });
  const GlobalMasterTemplate = IDL.Record({
    'signature' : IDL.Opt(ExternalBlob),
    'logo' : IDL.Opt(ExternalBlob),
    'layout' : LayoutSettings,
    'businessName' : IDL.Text,
    'businessAddress' : IDL.Text,
    'optionalCustomFieldValue' : IDL.Opt(IDL.Text),
    'stamp' : IDL.Opt(ExternalBlob),
    'optionalCustomFieldLabel' : IDL.Opt(IDL.Text),
    'adminId' : IDL.Text,
  });
  const TemplateResult = IDL.Variant({
    'unexpectedError' : IDL.Text,
    'alreadyExists' : IDL.Null,
    'unauthorizedField' : IDL.Null,
    'notFound' : IDL.Null,
    'success' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LoanType = IDL.Variant({
    'home' : IDL.Null,
    'education' : IDL.Null,
    'personal' : IDL.Null,
    'business' : IDL.Null,
    'vehicle' : IDL.Null,
  });
  const LoanProcessingData = IDL.Record({
    'id' : IDL.Text,
    'loanType' : LoanType,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
    'processingCharge' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const DocumentContent = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'adminId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomTemplate' : IDL.Func(
        [IDL.Text, GlobalMasterTemplate],
        [TemplateResult],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createLoanProcessingRecord' : IDL.Func([LoanProcessingData], [], []),
    'deleteLoanProcessingRecord' : IDL.Func([IDL.Text], [], []),
    'getAllDocumentContents' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'contents' : IDL.Vec(IDL.Text),
            'businessTemplates' : IDL.Opt(GlobalMasterTemplate),
          }),
        ],
        ['query'],
      ),
    'getAllLoanProcessingRecords' : IDL.Func(
        [],
        [IDL.Vec(LoanProcessingData)],
        ['query'],
      ),
    'getAllTemplates' : IDL.Func(
        [],
        [IDL.Vec(GlobalMasterTemplate)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomTemplateById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GlobalMasterTemplate)],
        ['query'],
      ),
    'getDocumentContent' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(DocumentContent)],
        ['query'],
      ),
    'getGlobalTemplate' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GlobalMasterTemplate)],
        ['query'],
      ),
    'getLoanProcessingRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(LoanProcessingData)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCustomTemplate' : IDL.Func(
        [IDL.Text, GlobalMasterTemplate],
        [TemplateResult],
        [],
      ),
    'updateGlobalTemplate' : IDL.Func([IDL.Text, GlobalMasterTemplate], [], []),
    'updateLoanProcessingRecord' : IDL.Func(
        [IDL.Text, LoanProcessingData],
        [],
        [],
      ),
    'updateMultipleDocumentTypes' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, DocumentContent))],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };