/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DocumentContent {
  'title' : string,
  'body' : string,
  'adminId' : string,
}
export type ExternalBlob = Uint8Array;
export interface GlobalMasterTemplate {
  'signature' : [] | [ExternalBlob],
  'logo' : [] | [ExternalBlob],
  'layout' : LayoutSettings,
  'businessName' : string,
  'businessAddress' : string,
  'optionalCustomFieldValue' : [] | [string],
  'stamp' : [] | [ExternalBlob],
  'optionalCustomFieldLabel' : [] | [string],
  'adminId' : string,
}
export interface LayoutSettings {
  'watermarkText' : string,
  'qrPayload' : string,
  'headerColor' : string,
  'watermarkOpacity' : bigint,
  'showQrCode' : boolean,
  'footerLayout' : { 'twoColumn' : null } |
    { 'centered' : null },
  'showWatermark' : boolean,
  'signatureLayout' : { 'stacked' : null } |
    { 'sideBySide' : null },
  'footerText' : string,
}
export interface LoanProcessingData {
  'id' : string,
  'loanType' : LoanType,
  'timestamp' : bigint,
  'amount' : bigint,
  'processingCharge' : bigint,
}
export type LoanType = { 'home' : null } |
  { 'education' : null } |
  { 'personal' : null } |
  { 'business' : null } |
  { 'vehicle' : null };
export type TemplateResult = { 'unexpectedError' : string } |
  { 'alreadyExists' : null } |
  { 'unauthorizedField' : null } |
  { 'notFound' : null } |
  { 'success' : null };
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomTemplate' : ActorMethod<
    [string, GlobalMasterTemplate],
    TemplateResult
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createLoanProcessingRecord' : ActorMethod<[LoanProcessingData], undefined>,
  'deleteLoanProcessingRecord' : ActorMethod<[string], undefined>,
  'getAllDocumentContents' : ActorMethod<
    [string],
    {
      'contents' : Array<string>,
      'businessTemplates' : [] | [GlobalMasterTemplate],
    }
  >,
  'getAllLoanProcessingRecords' : ActorMethod<[], Array<LoanProcessingData>>,
  'getAllTemplates' : ActorMethod<[], Array<GlobalMasterTemplate>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomTemplateById' : ActorMethod<[string], [] | [GlobalMasterTemplate]>,
  'getDocumentContent' : ActorMethod<[string, string], [] | [DocumentContent]>,
  'getGlobalTemplate' : ActorMethod<[string], [] | [GlobalMasterTemplate]>,
  'getLoanProcessingRecord' : ActorMethod<[string], [] | [LoanProcessingData]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCustomTemplate' : ActorMethod<
    [string, GlobalMasterTemplate],
    TemplateResult
  >,
  'updateGlobalTemplate' : ActorMethod<
    [string, GlobalMasterTemplate],
    undefined
  >,
  'updateLoanProcessingRecord' : ActorMethod<
    [string, LoanProcessingData],
    undefined
  >,
  'updateMultipleDocumentTypes' : ActorMethod<
    [string, Array<[string, DocumentContent]>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];